/** API route URLs — relative paths; base URL via env / proxy */
export const apiRoutes = {
  uploadDocument: "/api/upload-document",
  auth: {
    signup: "/api/auth/signup",
    login: "/api/auth/login",
    signout: "/api/auth/signout",
    verifyOtp: "/api/auth/verify-otp",
    resendSignupOtp: "/api/auth/resend-signup-otp",
    google: "/api/auth/google",
    googleCallback: "/api/auth/google/callback",
    forgotPassword: "/api/auth/forgot-password",
    verifyResetOtp: "/api/auth/verify-reset-otp",
    resetPassword: "/api/auth/reset-password",
  },
  signup: {
    social: "/api/signup/social",
  },
  user: {
    dashboardData: "/api/user/dashboard-data",
    profile: "/api/user/profile",
    aiQuestionnaireState: "/api/user/ai-questionnaire-state",
    jobs: "/api/user/jobs",
    job: (id: string) => `/api/user/jobs/${id}`,
    jobApply: (id: string) => `/api/user/jobs/${id}/apply`,
    applications: "/api/user/applications",
    jobsMatch: "/api/user/jobs/match",
    jobsIndustries: "/api/user/jobs/industries",
  },
  anam: {
    saveMessages: "/api/anam/save-messages",
    chatStream: "/api/anam/chat-stream",
    sessionToken: "/api/anam/session-token",
  },
  virtualAssistant: {
    getToken: "/api/virtual-assistant/get-token",
    dispatchAgent: "/api/virtual-assistant/dispatch-agent",
    milestoneTracker: "/api/virtual-assistant/milestone-tracker",
    notifySupport: "/api/virtual-assistant/notify-support",
  },
  questionnaire: {
    progress: "/api/questionnaire/progress",
    save: "/api/questionnaire/save",
    submit: "/api/questionnaire/submit",
  },
  admin: {
    bulkOnboard: "/api/admin/bulk-onboard",
    users: "/api/admin/users",
    industries: "/api/admin/industries",
    industry: (id: string) => `/api/admin/industries/${id}`,
    jobRoles: "/api/admin/job-roles",
    jobRole: (id: string) => `/api/admin/job-roles/${id}`,
  },
  recruiter: {
    auth: {
      signup: "/api/recruiter/auth/signup",
      login: "/api/recruiter/auth/login",
      logout: "/api/recruiter/auth/logout",
      verifyOtp: "/api/recruiter/auth/verify-otp",
      resendSignupOtp: "/api/recruiter/auth/resend-signup-otp",
      forgotPassword: "/api/recruiter/auth/forgot-password",
      verifyResetOtp: "/api/recruiter/auth/verify-reset-otp",
      resetPassword: "/api/recruiter/auth/reset-password",
    },
    company: "/api/recruiter/company",
    companyLogo: "/api/recruiter/company/logo",
    team: "/api/recruiter/team",
    teamInvite: "/api/recruiter/team/invite",
    teamInviteByToken: (token: string) => `/api/recruiter/team/invite/${token}`,
    teamInviteAccept: (token: string) =>
      `/api/recruiter/team/invite/${token}/accept`,
    teamMember: (memberId: string) =>
      `/api/recruiter/team/members/${memberId}`,
    teamMemberRole: (memberId: string) =>
      `/api/recruiter/team/members/${memberId}/role`,
    dashboard: "/api/recruiter/dashboard",
    jobs: "/api/recruiter/jobs",
    job: (id: string) => `/api/recruiter/jobs/${id}`,
    jobApplications: (id: string) => `/api/recruiter/jobs/${id}/applications`,
    jobApplicationStatus: (jobId: string, applicationId: string) =>
      `/api/recruiter/jobs/${jobId}/applications/${applicationId}`,
    jobPublish: (id: string) => `/api/recruiter/jobs/${id}/publish`,
    jobClose: (id: string) => `/api/recruiter/jobs/${id}/close`,
    jobEnhance: (id: string) => `/api/recruiter/jobs/${id}/enhance`,
    jobEnhanceDraft: "/api/recruiter/jobs/enhance-draft",
    jobEmbedding: (id: string) => `/api/recruiter/jobs/${id}/embedding`,
    catalogIndustries: "/api/recruiter/catalog/industries",
    catalogJobRoles: "/api/recruiter/catalog/job-roles",
    matchJobs: "/api/recruiter/match/jobs",
  },
} as const;
