import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { AppProviders } from "@/components/providers/AppProviders";
import "./globals.css";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  display: "swap",
});

/**
 * Icons come from App Router file conventions (`app/icon.png`, `app/apple-icon.png`,
 * `app/favicon.ico`) so Next serves content-hashed URLs and favicon updates are not stuck
 * on a stale `/favicon.png` cache. Keep `public/favicon.png` in sync for direct asset use.
 */
export const metadata: Metadata = {
  title: "Numee",
  description: "Generated by Numee developers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakarta.variable} antialiased font-sans`}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
